### Request 1: Create a transaction
### Status Code: 201
### Response Body: JSON containing the newly created transaction
### Repsonse type: application/json
POST http://127.0.0.1:5000//api/transactions HTTP/1.1
content-type: application/json

{
    "date": "2025-11-15",
    "amount": 20.25,
    "memo": "pizzanista lunch"
}

### Request 2: Create a transaction with no date input
### Status Code: 201
### Response Body: JSON containing the newly created transaction
### Repsonse type: application/json
POST http://127.0.0.1:5000//api/transactions HTTP/1.1
content-type: application/json

{
    "amount": 10.25,
    "memo": "coffee with Hayley"
}

### Request 3: Get all Transactions
### Status Code: 200
### Response Body: array of the two transactions represented as dicts
GET http://127.0.0.1:5000/api/transactions HTTP/1.1
content-type: application/json

### Request 4: Update a transaction
### Status Code: 200
### Response Body: JSON containing the updated dicitonary
PUT http://127.0.0.1:5000/api/transactions/1 HTTP/1.1
content-type: application/json

{
    "amount": 18.00
}

### Request 5: Update a transaction for an id that doesn't exist
### Status Code: 404
### Response Body: JSON containing the updated dicitonary
PUT http://127.0.0.1:5000/api/transactions/10 HTTP/1.1
content-type: application/json

{
    "memo": "does this exist?"
}

### Request 6: Create a transaction 
### Status Code: 201
### Response Body: JSON containing the newly created transaction
### Repsonse type: application/json
POST http://127.0.0.1:5000/api/transactions HTTP/1.1
content-type: application/json

{
    "date": "11/10/25",
    "amount": 125.36,
    "memo": "dinner with friends"
}

### Request 7: Get total spend 
### Status Code: 200
### Response Body: JSON object containing the sum of amount column 
GET http://127.0.0.1:5000/api/transactions/total-spend HTTP/1.1
content-type: application/json

### Request 8: Get remaining
### Status Code: 200
### Response Body: JSON object containing the remaining available to spend
GET http://127.0.0.1:5000/api/transactions/remaining HTTP/1.1
content-type: application/json

{
    "budget": 500
}

### Request 9: Delete transaction by id
### Status Code: 204
### Response Body: No content
DELETE http://127.0.0.1:5000/api/transactions/1 HTTP/1.1
content-type: application/json

### Request 10: Delete transaction with no matching ID
### Status Code: 404
### Response Body: { "error": "not found" }
DELETE http://127.0.0.1:5000/api/transactions/10 HTTP/1.1
content-type: application/json

### Request 11: Get all Transactions
### Status Code: 200
### Response Body: array of the two transactions represented as dicts, the first transaction deleted
GET http://127.0.0.1:5000/api/transactions HTTP/1.1
content-type: application/json

### Request 12: Delete all transactions
### Status Code: 204
### Response Body: No content
DELETE http://127.0.0.1:5000/api/transactions HTTP/1.1
content-type: application/json

### Request 13: Get all Transactions
### Status Code: 200
### Response Body: an empty array
GET http://127.0.0.1:5000/api/transactions HTTP/1.1
content-type: application/json

###################### Summary Table Tests #########################

### Request 1: Create a summary
### Status Code: 201
### Response Body: JSON containing the newly created summary
### Repsonse type: application/json
POST http://127.0.0.1:5000/api/summaries HTTP/1.1
content-type: application/json

### Request 2: Get a summary
### Status Code: 200
### Response Body: JSON containing the newly created transaction
### Repsonse type: application/json
GET http://127.0.0.1:5000/api/summaries/1 HTTP/1.1
content-type: application/json

### Request 3: Update a summary
### Status Code: 200
### Response Body: JSON containing the newly created transaction
### Repsonse type: application/json
PUT http://127.0.0.1:5000/api/summaries/1 HTTP/1.1
content-type: application/json

{
    "budget": 200,
    "last_updated": "2025-11-15"
}

### Request 4: Delete a summary
### Status Code: 201
### Response Body: JSON containing the newly created transaction
### Repsonse type: application/json
DELETE http://127.0.0.1:5000/api/summaries/1 HTTP/1.1
content-type: application/json

### Request 5: Get a summary
### Status Code: 404
### Response Body: {"error": "not found"}
### Repsonse type: application/json
GET http://127.0.0.1:5000/api/summaries/1 HTTP/1.1
content-type: application/json

### Request 6: Get all summaries
### Status Code: 200
### Response Body: JSON containing the newly created transaction
### Repsonse type: application/json
GET http://127.0.0.1:5000/api/summaries HTTP/1.1
content-type: application/json

### Request 6: Delete all summaries
### Status Code: 204
### Response Body: JSON containing the newly created transaction
### Repsonse type: application/json
DELETE http://127.0.0.1:5000/api/summaries HTTP/1.1
content-type: application/json